# WEEK 1

## 1. Python Function:

`add_numbers` is a function that takes two numbers and adds them together.

In [1]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

optional parameters can be set to default values to avoid *Method Overloading*. `add_numbers` has optional 3rd parameter

In [2]:
def add_numbers(x, y, z=None):
    if z is None:
        return x + y
    else:
        return x + y + z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


`add_numbers` updated to take an optional flag parameter.

In [3]:
def add_numbers(x, y, z=None, flag=True):
    if flag is True:
        print("Flag is True")
    if z is None:
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is True
3


Function `add_numbers` assigned to variable a.

In [4]:
def add_numbers(x, y):
    return x + y

a = add_numbers
a(1, 2)

3

## 2. Types and Sequences:

Python is a dynamic type language but that doesn't mean there aren't any types. Python has a `type()` function which tells the type pf input parameter.  

In [5]:
# string
type('A String')

str

In [6]:
# none type
type(None)

NoneType

In [7]:
# integers
type(1)

int

In [8]:
# floating point numbers
type(1.0)

float

In [9]:
# functions
type(add_numbers)

function

### Three native types of sequence or collections:
 - Tuples ()
 - Lists []
 - Dictionaries {}

Tuple is immutable(cannot be altered) list of variables.

In [10]:
x = (1, 'a', 2, 'b')
type(x)

tuple

List is mutable data structure.

In [11]:
x = [1, 'a', 2, 'b']
type(x)

list

Use `append` to append an object to a list

In [12]:
x.append('y')
x

[1, 'a', 2, 'b', 'y']

Loop to iterate through each item in list or tuple.

In [13]:
for item in x:
    print(item)

1
a
2
b
y


Or use indexing operator.

In [14]:
i = 0
while i != len(x):
    print(x[i])
    i = i + 1

1
a
2
b
y


Use `+` to concatenate lists

In [15]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

Use `*` to repeat the list items.

In [16]:
[1, 2] * 3

[1, 2, 1, 2, 1, 2]

Use `in` to check items inside the list

In [17]:
1 in [1, 2, 3, 4]

True

A powerful concept in Python called **Slicing Structure**.

In [18]:
x = "This is a string"
print(x[0]) # first character i.e. T

T


In [19]:
print(x[0:1]) # first character but end setup explicitly i.e. T

T


In [20]:
print(x[0:2]) # first two characters i.e. Th

Th


In [21]:
print(x[-1]) # last character i.e. g

g


In [22]:
print(x[-4:-2]) # slice from 4th last character to before 2nd last character i.e. ri

ri


In [23]:
print(x[:3]) # slice from beginning until third character i.e. Thi

Thi


In [24]:
print(x[3:]) # slice from 4th character till last character i.e. s is a string

s is a string


As string is a list of characters so list operations such as concatenation, replication and checking items inside a list is same for strings.

In [25]:
firstname = "Christopher"
lastname = "Brook"

print(firstname + ' ' + lastname) # concatenation
print(firstname * 3) # replication
print('Chris' in firstname) # checking inside a string

Christopher Brook
ChristopherChristopherChristopher
True


`split` returns a list of all the words in a string, or a list split on a specific character.

In [26]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Christopher
Brooks


Numbers should be explicitly converted to string when concatenated with strings.

In [27]:
'Chris' + str(2)

'Chris2'

Dictionaries are a collection of key,value pairs i.e. every value is associated with a key and a key is used to get the value. Dictionaries in other languages are known as *map*.

In [28]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using its key

'brooksch@umich.edu'

In [29]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

Iterate over the keys:

In [30]:
for name in x:
    print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


Iterate over the values:

In [31]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


Iterate over both the keys and values in items:

In [32]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


Unpacking a sequence into multiple variables in single assignment

In [33]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [34]:
fname

'Christopher'

In [35]:
lname

'Brooks'

In [36]:
email

'brooksch@umich.edu'

## 3. More on Strings:

Python uses placeholders inside the string to evaluate the variables and manipulate into string without using str().

In [37]:
sales_record = {'price': 3.24,
               'num_items': 4,
               'person': 'Chris'}
sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}.'

print(sales_statement.format(sales_record['person'],
     sales_record['num_items'],
     sales_record['price'],
     sales_record['num_items'] * sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96.


## 4. Reading and Writing CSV Files:

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmissionm
* year : model year

In [38]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg # The first three dictionaries in our list.

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [39]:
len(mpg)

234

In [40]:
mpg[0].keys()

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [41]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

In [42]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

In [43]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

In [44]:
cityMpgByCycle = []
# for every cyclinder in cylinders
for cylinder in cylinders:
    # reset sum
    sumMpg = 0
    # reset counter
    cylinderCount = 0
    # iterate over all dicts in mpg
    for dicts in mpg:
        # if cyclinder of dicts matches cyclinder in cyclinders
        if dicts['cyl'] == cylinder:
            # sum the dicts cyclinder city fuel
            sumMpg += float(dicts['cty'])
            # increment the counter
            cylinderCount += 1
    #compute average = sum / counter and append cylinder and average to list
    cityMpgByCycle.append((cylinder, sumMpg / cylinderCount))
cityMpgByCycle.sort(key=lambda x: x[0])
cityMpgByCycle
    

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [45]:
vehicleClasses = set(d['class'] for d in mpg)
vehicleClasses

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [46]:
hwyMpgByClass = []
# for every vehicleClass in vehicleClasses
for vehicleClass in vehicleClasses:
    # reset sum
    sumMpg = 0
    # reset counter
    vehicleCount = 0
    # iterate over all dicts in mpg
    for dicts in mpg:
        # if class of dicts matches vehicleClass in vehicleClasses
        if dicts['class'] == vehicleClass:
            # sum the dicts highway fuel
            sumMpg += float(dicts['hwy'])
            # increment the counter
            vehicleCount += 1
    #compute average = sum / counter and append vehicleClass and average to list
    hwyMpgByClass.append((vehicleClass, sumMpg / vehicleCount))
hwyMpgByClass.sort(key=lambda x: x[1])
hwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

## 5. Dates and Time

In [47]:
import datetime as dt
import time as tm

`time()` return the current time in seconds since January 1st, 1970

In [48]:
tm.time()

1533460561.94

Convert timestamp to datetime

In [49]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2018, 8, 5, 14, 16, 2, 84210)

Different attributes of `datetime`

In [50]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2018, 8, 5, 14, 16, 2)

`timedelta` is the duration expressing difference between two dates

In [51]:
# create a time difference of 100 days
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(100)

`date.today()` returns the current local date

In [52]:
today = dt.date.today()
today

datetime.date(2018, 8, 5)

In [53]:
# date 100 days ago
today - delta

datetime.date(2018, 4, 27)

In [54]:
# comparing dates
today > today-delta

True

## 6. Objects and map()

Time for some Object-Oriented Python
<br>
Declare any class with a `class` keyword and then everything below is within that class scope.

In [55]:
class Person:
    department = "School of Information"
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [56]:
# create an object of class
person = Person()
person.set_name("Maliha Sameen")
person.set_location("Pakistan")
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Maliha Sameen live in Pakistan and works in the department School of Information


`map()` is one of the basics in functional programming in python. Functional programming is a programming paradigm in which you declare all the parameters explicitly which could change through execution of a given function. Thus functional programming refers to as being side effect free.

Here's an example of mapping the min function between two lists.

In [57]:
store1 = [10.00, 11.10, 12.34, 2.34]
store2 = [9.00, 11.60, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [58]:
for item in cheapest:
    print(item)

9.0
11.1
12.34
2.01


**Exercise:**
Here is a list of faculty teaching this MOOC. Can you write a function and apply it using map() to get a list of all faculty titles and last names (e.g. ['Dr. Brooks', 'Dr. Collins-Thompson', …]) ?

In [59]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + " " + person.split()[-1]

list(map(split_title_and_name, people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

## 7. Lambda and List Comprehensions

Lambdas are anonymous functions that are easy and short lived and it's easier to write out the function in one line than creating a seperate named function but lamdas are limited because only one expression can be written and it shouldn't contain complex logic.

In [60]:
#create a lambda taking three parameters and add first two
add_function = lambda a, b, c : a + b
add_function(1, 2, 3)

3

**Exercise:**
Use lambda to get titles and lastnames.

In [61]:
# list of people
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson',
          'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

# option 1
for person in people:
    print(split_title_and_name(person) == (lambda x: x.split()[0] 
          + ' ' + x.split()[-1])(person))

# option 2
list(map(split_title_and_name, people)) == list(map(lambda 
    x: x.split()[0] + ' ' + x.split()[-1], people))

True
True
True
True


True

Just like lambdas, list comprehensions are also a compact way and is much faster.

Here is an example to display a list of even numbers in range(0, 1000)

In [62]:
even_numbers_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        even_numbers_list.append(number)
even_numbers_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [63]:
# now doing same thing with list comprehension
even_numbers_list = [number for number in range(0, 1000) if number % 2 == 0]
even_numbers_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

**Exercise:**
Convert a function into a list comprehension.

In [64]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range (10) for j in range(10)]

True

## 8. NumPy Library:

In [65]:
import numpy as np

### Creating an Arrays:
Create a list and then convert into array.

In [66]:
mylist = [1, 2, 3]
np.array(mylist)

array([1, 2, 3])

We can also pass a list directly to numpy array.

In [67]:
np.array([1, 2, 3])

array([1, 2, 3])

We can pass list of lists to create multidimensional arrays

In [68]:
m = np.array([[1,2,3], [4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

`shape` attribute is used to check dimensions i.e. (rows, columns).

In [69]:
m.shape

(2, 3)

`np.arange()` returns evenly spaced values between an interval. 

In [70]:
# np.arange(a, b, c) starts from a till b with step size of c
n = np.arange(0, 30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

`reshape(a, b)` converts a list to matrix with a rows and b columns without modifying the current list.

In [71]:
n.reshape(3, 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

`np.linspace()` is similar to `np.arange()` except for one thing that we provide the number of elements we want between a specified interval and it splits according to the number of elements we want.

In [72]:
# np.linspace(a, b, c) returns c evenly spaced values between a and b inclusive.
o = np.linspace(0, 4, 9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

`resize()` is used to change the dimensions inplace with modifying current list.

In [73]:
o.resize(3,3) #resize list to 3x3 matrix 
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

`ones()` returns an array with given shape and type filled with ones

In [74]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

`zeros()` returns an array with given shape and type filled with zeros.

In [75]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

`eye(n)` creates an identity matrix of n dimensions.

In [76]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

`diag()` extracts a diagonal or construct a diagonal array

In [77]:
y = [4,5,6]
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [78]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [79]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combining Arrays

In [80]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

use `vstack()` to stack elements row wise

In [81]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

use `hstack()` to stack elements column wise

In [82]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### Operations
Basic operations on matrices

In [83]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [84]:
print(x + y) # elementwise addition
print(x - y) # elementwise subtraction
print(x * y) # elementwise multiplication
print(x / y) # elementwise division
print(x ** 2) # elementwise power [1,2,3] ^ 2

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [85]:
x.dot(y) # dot product

32

In [86]:
z = np.array([y, y**2])
len(z) # no. of rows of array

2

**Transposing:**
<br>
$  A = \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
 T(A) = \begin{bmatrix}x_1 \\ x_2 \\ x_3\end{bmatrix}$
 <br>
Transposing a matrix reverse its dimensions. `.T` is used to take transpose of a matrix.<br>
The dimensions of z before transposing is (2,3)

In [87]:
z.shape

(2, 3)

In [88]:
# now taking transpose
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

After taking transpose the rows are swapped with the columns.

In [89]:
z.T.shape

(3, 2)

In [90]:
# .dtype is used to see the data type of elements in array
z.dtype

dtype('int32')

In [91]:
# use .astype() to cast a specific datatype to array elements.
z = z.astype('f')
z.dtype

dtype('float32')

### Math Functions:

In [92]:
a = np.array([-4, -2, 1, 3, 5])

In [93]:
# sum of all elements in the array
a.sum()

3

In [94]:
# max element in the array
a.max()

5

In [95]:
# min element in the array
a.min()

-4

In [96]:
# mean of elements in the array
a.mean()

0.6

In [97]:
# standard deviation of elements in the array
a.std()

3.2619012860600183

In [99]:
# returns index of max element in the array
a.argmax()

4

In [98]:
# returns index of min element in the array
a.argmin()

0